[package]
name = "cw-grant-spec"
version = { workspace = true }
authors = ["Marc <marc@yieldmos.com>"]
description = "Helper types and functions for specifying Authz grants that should be set before contract use"
edition = { workspace = true }

[dependencies]
# withdraw-rewards-tax-grant = { path = "../../contracts/withdraw_rewards_tax", features = [
#     "msgs",
# ] }
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
