[package]
name = "authzpp-utils"
version = { workspace = true }
authors = ["Marc <marc@yieldmos.com>"]
description = "Utility functions used by Authzpp contracts"
edition = { workspace = true }

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
cw-storage-plus = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
cosmos-sdk-proto = { workspace = true }
osmosis-std = { workspace = true }


osmosis-test-tube = { workspace = true }
